### ISSUE TITLE
DLL Libraries Import Python

### ISSUE THREAD

**Issue by NicoloRaceOn** [mat-docs/MAT.OCS.SQLRace.Examples#37]
Hi everyone,

I've been trying in those days the example python code available [here ](https://github.com/mat-docs/MAT.OCS.SQLRace.Examples) but i keep getting this error when importing libraries:
![{F2BE61CB-9A37-44E6-ACD0-2B44D653E167}](https://github.com/user-attachments/assets/ec5ce17e-56d7-4593-9dfd-10ea6348d79a)

I've tried the following, but the error remains:

- python version (3.9 & 3.12)
- .NET Framework 8.0 (as far as i red, this should be compatible with the required .NET 4.8)
- added nugeet packages

I already made sure that the library is located at the correct path (Atlas 10 default installation folder).

If you please have any suggestion on how to try to solve this issue, that would be really welcome :)
Thanks in advance

**Comment by salman-mclarenapplied** [comment]
Hi,

This issue is because ATLAS uses .NET 6 and all of our SQL Race libraries and APIs have been updated to .NET 6. I have attached a pull request which has a fix to load the required libraries. In essence, you will need the following change at the beginning of your Python code:

```
from pythonnet import load

load("coreclr", runtime_config=r"C:\Program Files\McLaren Applied Technologies\ATLAS 10\MAT.Atlas.Host.runtimeconfig.json")

import clr # Pythonnet
```
This will load the correct clr for Pythonnet which is compatible with .NET core.

**Comment by NicoloRaceOn** [comment]
Hi Salman,

thanks this seems solving the issue.

Do you have any suggestions on how to solve similar problem, but using matlab instead of python?
Thanks again
Regards

**Comment by salman-mclarenapplied** [comment]
Hi Nicolo,

We have instructions for matlab [here](https://atlas.mclarenapplied.com/developer/net6-upgrade/) which should fix this issue. 

Many Thanks,
Salman

**Comment by NicoloRaceOn** [comment]
Hi again, i'm back again on this topic :)

I'm now getting to this line of code of the script:
app.Connect(Path.GetFileNameWithoutExtension(AppDomain.CurrentDomain.FriendlyName))

and this is the error message:
![image](https://github.com/user-attachments/assets/3d2b25e0-0468-4aca-a694-94d171716f66)

What I figured out so far is that this function is grabbing the domain of the python interpreter, however, it probably needs the domain of the subprocess in which Atlas is opened. But there is no way in Python to figure that out.

Can you please let me know how to solve this error?
Thanks
